In [25]:
import geopandas as gpd
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
import matplotlib.pyplot as plt
from shapely.geometry import LineString, Point
import json
import os

In [ ]:
# uncomment and run below if you don't have the required packages
# pip install pandas geopandas matplotlib shapely numpy os json

In [2]:
def convert_to_geodataframe(df):
    # Create a copy of the dataframe to avoid modifying the original
    gdf = df.copy()
    
    # Convert the coordinates to shapely Point objects
    gdf['geometry'] = gdf['coords'].apply(lambda x: shp.geometry.Point(x[0], x[1]))  # Note: Point(lat, lon)
    
    # Create the GeoDataFrame
    gdf = gpd.GeoDataFrame(gdf, geometry='geometry')
    
    # Set the coordinate reference system (CRS) to WGS84
    gdf.set_crs(epsg=4326, inplace=True)
    
    return gdf

In [3]:
local_path = "/Volumes/samsung-4tb/b2p/impact-model/no_order_1_less_than_500m_with_top_sites/model_outputs"
et_bridge_view_path = local_path + "/ethiopia/joined_data/bridge_view_data.parquet"
et_travel_paths_health_posts_path = local_path + "/ethiopia/joined_data/travel_paths_to_health_posts_optimal.parquet"

In [4]:
array_cols = [ "subregion_indices", "coords", "used_by_cells_for_semi_dense_urban_optimal", "used_by_h3_for_semi_dense_urban_optimal", "used_by_cells_for_health_posts_optimal", "used_by_h3_for_health_posts_optimal", "used_by_cells_for_primary_schools_fixed", "used_by_h3_for_primary_schools_fixed", "used_by_cells_for_all_health_facilities_optimal", "used_by_h3_for_all_health_facilities_optimal", "used_by_cells_for_health_centers_optimal", "used_by_h3_for_health_centers_optimal", "used_by_cells_for_major_hospitals_optimal", "used_by_h3_for_major_hospitals_optimal", "used_by_cells_for_major_roads_optimal", "used_by_h3_for_major_roads_optimal", "used_by_cells_for_secondary_schools_fixed", "used_by_h3_for_secondary_schools_fixed", "used_by_cells_for_all_education_facilities_fixed", "used_by_h3_for_all_education_facilities_fixed", ]

In [5]:
et_bridge_view = pd.read_parquet(et_bridge_view_path)
print("bridge view done")

bridge view done


In [6]:
et_travel_paths_health_posts = pd.read_parquet(et_travel_paths_health_posts_path)

In [13]:
for c in et_bridge_view.columns:
    print (c)

index
type
geometry
subregion_indices
coords
exit_point_index
used_by_cells_for_semi_dense_urban_optimal
used_by_h3_for_semi_dense_urban_optimal
used_by_cells_for_health_posts_optimal
used_by_h3_for_health_posts_optimal
used_by_cells_for_primary_schools_fixed
used_by_h3_for_primary_schools_fixed
used_by_cells_for_all_health_facilities_optimal
used_by_h3_for_all_health_facilities_optimal
used_by_cells_for_health_centers_optimal
used_by_h3_for_health_centers_optimal
used_by_cells_for_major_hospitals_optimal
used_by_h3_for_major_hospitals_optimal
used_by_cells_for_major_roads_optimal
used_by_h3_for_major_roads_optimal
used_by_cells_for_secondary_schools_fixed
used_by_h3_for_secondary_schools_fixed
used_by_cells_for_all_education_facilities_fixed
used_by_h3_for_all_education_facilities_fixed


In [14]:
for c in et_travel_paths_health_posts.columns:
    print (c)

row
col
subregion
coords
exit_point_used
exit_point_index
destination_index
destination_coords
exit_point_index_path
h3_index
exit_point_path
path_to_exit_point
exit_point_used_no_sites
exit_point_path_no_sites
destination_coords_no_sites
path_to_exit_point_no_sites


In [16]:
et_travel_paths_health_posts

row    col  subregion                  coords   
0         12427   8836     586947  [40.363335, 4.5433335]  \
1         12427   8837     586947  [40.364166, 4.5433335]   
2         12427   8838     586947     [40.365, 4.5433335]   
3         12427   8839     586947  [40.365833, 4.5433335]   
4         12428   8836     586947     [40.363335, 4.5425]   
...         ...    ...        ...                     ...   
21677995   6471  10408     694516   [41.673332, 9.506667]   
21677996   6472  10401     694516     [41.6675, 9.505834]   
21677997   6472  10405     694516   [41.670834, 9.505834]   
21677998   6473  10401     694516        [41.6675, 9.505]   
21677999   6473  10406     694516      [41.671665, 9.505]   

              exit_point_used  exit_point_index  destination_index   
0                        None                 0                  0  \
1                        None                 0                  0   
2                        None                 0                  0   
3                        None                 0                  0   
4                        None                 0                  0   
...                       ...               ...                ...   
21677995  [41.66769, 9.50442]           1123475               1473   
21677996  [41.66769, 9.50442]           1123475               1473   
21677997  [41.66769, 9.50442]           1123475               1473   
21677998  [41.66769, 9.50442]           1123475               1473   
21677999  [41.66769, 9.50442]           1123475               1473   

           destination_coords              exit_point_index_path   
0                        None                               None  \
1                        None                               None   
2                        None                               None   
3                        None                               None   
4                        None                               None   
...                       ...                                ...   
21677995  [41.69781, 9.51598]  [1123475, 182826, 396748, 784200]   
21677996  [41.69781, 9.51598]  [1123475, 182826, 396748, 784200]   
21677997  [41.69781, 9.51598]  [1123475, 182826, 396748, 784200]   
21677998  [41.69781, 9.51598]  [1123475, 182826, 396748, 784200]   
21677999  [41.69781, 9.51598]  [1123475, 182826, 396748, 784200]   

                 h3_index                                    exit_point_path   
0         887aeeba5dfffff                                               None  \
1         887aeeba5dfffff                                               None   
2         887aeeba5dfffff                                               None   
3         887aeeba5dfffff                                               None   
4         887aeeba5dfffff                                               None   
...                   ...                                                ...   
21677995  887ada962dfffff  [[41.66769, 9.50442], [41.67111, 9.49388], [41...   
21677996  887ada962dfffff  [[41.66769, 9.50442], [41.67111, 9.49388], [41...   
21677997  887ada962dfffff  [[41.66769, 9.50442], [41.67111, 9.49388], [41...   
21677998  887ada962dfffff  [[41.66769, 9.50442], [41.67111, 9.49388], [41...   
21677999  887ada962dfffff  [[41.66769, 9.50442], [41.67111, 9.49388], [41...   

                                         path_to_exit_point   
0                                                        []  \
1                                                        []   
2                                                        []   
3                                                        []   
4                                                        []   
...                                                     ...   
21677995  [[41.673332, 9.506667], [41.6725, 9.5075], [41...   
21677996  [[41.6675, 9.505834], [41.6675, 9.505], [41.66...   
21677997  [[41.670834, 9.505834], [41.67, 9.506667], [41...   
21677998            [[41.6675,

In [37]:
# create a data frame where h3_index matches 887ada962dfffff
hex = et_travel_paths_health_posts[et_travel_paths_health_posts["h3_index"] == "887ada962dfffff"]
hex


row    col  subregion                 coords      exit_point_used  \
13322219  6474  10401     694508    [41.66769, 9.50442]  [41.66769, 9.50442]   
13322223  6475  10402     694508  [41.668335, 9.503333]  [41.67111, 9.49388]   
13322224  6475  10403     694508  [41.669167, 9.503333]  [41.67111, 9.49388]   
13322225  6475  10404     694508      [41.67, 9.503333]  [41.67111, 9.49388]   
13322226  6475  10405     694508  [41.670834, 9.503333]  [41.67111, 9.49388]   
13322227  6475  10406     694508  [41.671665, 9.503333]  [41.67111, 9.49388]   
13322228  6475  10407     694508    [41.6725, 9.503333]  [41.67111, 9.49388]   
13322229  6475  10408     694508  [41.673332, 9.503333]  [41.67111, 9.49388]   
13322230  6475  10409     694508  [41.674168, 9.503333]  [41.67111, 9.49388]   
21677987  6470  10402     694516    [41.668335, 9.5075]  [41.66769, 9.50442]   
21677988  6470  10403     694516    [41.669167, 9.5075]  [41.66769, 9.50442]   
21677989  6470  10404     694516        [41.67, 9.5075]  [41.66769, 9.50442]   
21677990  6470  10405     694516    [41.670834, 9.5075]  [41.66769, 9.50442]   
21677991  6470  10406     694516    [41.671665, 9.5075]  [41.66769, 9.50442]   
21677992  6470  10407     694516      [41.6725, 9.5075]  [41.66769, 9.50442]   
21677993  6471  10401     694516    [41.6675, 9.506667]  [41.66769, 9.50442]   
21677994  6471  10404     694516      [41.67, 9.506667]  [41.66769, 9.50442]   
21677995  6471  10408     694516  [41.673332, 9.506667]  [41.66769, 9.50442]   
21677996  6472  10401     694516    [41.6675, 9.505834]  [41.66769, 9.50442]   
21677997  6472  10405     694516  [41.670834, 9.505834]  [41.66769, 9.50442]   
21677998  6473  10401     694516       [41.6675, 9.505]  [41.66769, 9.50442]   
21677999  6473  10406     694516     [41.671665, 9.505]  [41.66769, 9.50442]   

          exit_point_index  destination_index   destination_coords  \
13322219           1123475               1473  [41.69781, 9.51598]   
13322223            182826               1473  [41.69781, 9.51598]   
13322224            182826               1473  [41.69781, 9.51598]   
13322225            182826               1473  [41.69781, 9.51598]   
13322226            182826               1473  [41.69781, 9.51598]   
13322227            182826               1473  [41.69781, 9.51598]   
13322228            182826               1473  [41.69781, 9.51598]   
13322229            182826               1473  [41.69781, 9.51598]   
13322230            182826               1473  [41.69781, 9.51598]   
21677987           1123475               1473  [41.69781, 9.51598]   
21677988           1123475               1473  [41.69781, 9.51598]   
21677989           1123475               1473  [41.69781, 9.51598]   
21677990           1123475               1473  [41.69781, 9.51598]   
21677991           1123475               1473  [41.69781, 9.51598]   
21677992           1123475               1473  [41.69781, 9.51598]   
21677993           1123475               1473  [41.69781, 9.51598]   
21677994           1123475               1473  [41.69781, 9.51598]   
21677995           1123475               1473  [41.69781, 9.51598]   
21677996           1123475               1473  [41.69781, 9.51598]   
21677997           1123475               1473  [41.69781, 9.51598]   
21677998           1123475               1473  [41.69781, 9.51598]   
21677999           1123475               1473  [41.69781, 9.51598]   

                      exit_point_index_path         h3_index  \
13322219  [1123475, 182826, 396748, 784200]  887ada962dfffff   
13322223           [182826, 396748, 784200]  887ada962dfffff   
13322224           [182826, 396748, 784200]  887ada962dfffff   
13322225           [182826, 396748, 784200]  887ada962dfffff   
13322226           [182826, 396748, 784200]  887ada962dfffff   
13322227           [182826, 396748, 784200]  887ada962dfffff   
13322228           [182826, 396748, 784200]  887ada962dfffff   
13322229           [182826, 396748, 784200]  88

In [16]:
# create a dataframe with row col and exit_point_path called exit_point_path
exit_point_path = et_travel_paths_health_posts[["row", "col", "exit_point_path"]]
path_to = et_travel_paths_health_posts[['row', 'col', "path_to_exit_point"]]

In [39]:
def convert_to_geodataframe(df, path_column, crs='EPSG:4326'):
    """
    Convert a DataFrame with array coordinate paths to a GeoDataFrame.
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The input DataFrame containing the coordinate arrays
    path_column : str, default 'path_to_exit_point'
        The column name containing the array of coordinate points
    crs : str, default 'EPSG:4326'
        The coordinate reference system (WGS84 by default)
        
    Returns:
    --------
    geopandas.GeoDataFrame
        A GeoDataFrame with geometries created from the coordinate arrays
    """
    # Create a copy to avoid modifying the original
    gdf = df.copy()
    
    # Convert the arrays to LineString geometries
    def create_geometry(coord_array):
        if not isinstance(coord_array, np.ndarray):
            return None
            
        # Check if the array is empty or has only one point
        if len(coord_array) == 0:
            return None
        elif len(coord_array) == 1:
            # For single points, create a Point geometry instead
            point = coord_array[0]
            return Point(point[0], point[1])  # lon, lat
        else:
            try:
                # Extract coordinates as (lon, lat) pairs
                coords = [(point[0], point[1]) for point in coord_array]
                return LineString(coords)
            except Exception as e:
                print(f"Error creating LineString: {e}")
                print(f"Coordinates: {coord_array}")
                return None
    
    # Apply the conversion to each row
    gdf['geometry'] = gdf[path_column].apply(create_geometry)
    
    # Drop rows with None geometries
    gdf = gdf.dropna(subset=['geometry'])
    
    # Convert to GeoDataFrame
    gdf = gpd.GeoDataFrame(gdf, geometry='geometry', crs=crs)
    
    return gdf

In [42]:
hex_gdf.explore()

In [44]:
hex_gdf = convert_to_geodataframe(hex, 'exit_point_path')
hex_gdf.explore()

In [45]:
# how many unique geometries are there in the hex_gdf
hex_gdf['geometry'].nunique()

2

In [30]:
path_to_test = convert_to_geodataframe(path_to.head(1000))
path_to_test

row   col                                 path_to_exit_point  \
12   2712  4483  [[36.735832, 12.639167], [36.736668, 12.638333...   
13   2713  4483  [[36.735832, 12.638333], [36.736668, 12.6375],...   
14   2713  4484  [[36.736668, 12.638333], [36.7375, 12.6375], [...   
15   2714  4484  [[36.736668, 12.6375], [36.7375, 12.636667], [...   
16   2714  4485  [[36.7375, 12.6375], [36.7375, 12.636667], [36...   
..    ...   ...                                                ...   
995  4650  6199  [[38.165833, 11.024167], [38.165, 11.023334], ...   
996  4651  6197  [[38.164165, 11.023334], [38.165, 11.023334], ...   
997  4651  6198  [[38.165, 11.023334], [38.165833, 11.0225], [3...   
998  4651  6200  [[38.166668, 11.023334], [38.165833, 11.0225],...   
999  4652  6199  [[38.165833, 11.0225], [38.166668, 11.0225], [...   

                                              geometry  
12   LINESTRING (36.73583 12.63917, 36.73667 12.638...  
13   LINESTRING (36.73583 12.63833, 36.73667 12.637...  
14   LINESTRING (36.73667 12.63833, 36.7375 12.6375...  
15   LINESTRING (36.73667 12.6375, 36.7375 12.63667...  
16   LINESTRING (36.7375 12.6375, 36.7375 12.63667,...  
..                                                 ...  
995  LINESTRING (38.16583 11.02417, 38.165 11.02333...  
996  LINESTRING (38.16417 11.02333, 38.165 11.02333...  
997  LINESTRING (38.165 11.02333, 38.16583 11.0225,...  
998  LINESTRING (38.16667 11.02333, 38.16583 11.022...  
999  LINESTRING (38.16583 11.0225, 38.16667 11.0225...  

[981 rows x 4 columns]

In [32]:
path_from_test = convert_to_geodataframe(exit_point_path.head(1000), path_column='exit_point_path')
path_from_test["geometry"].explore()

In [31]:
path_to_test["geometry"].explore()

In [ ]:
# join the two dataframes
path_to_test["path_type"] = "to"
path_from_test["path_type"] = "from"
paths = pd.concat([path_to_test, path_from_test], ignore_index=True)
paths

row   col                                 path_to_exit_point  \
0     2712  4483  [[36.735832, 12.639167], [36.736668, 12.638333...   
1     2713  4483  [[36.735832, 12.638333], [36.736668, 12.6375],...   
2     2713  4484  [[36.736668, 12.638333], [36.7375, 12.6375], [...   
3     2714  4484  [[36.736668, 12.6375], [36.7375, 12.636667], [...   
4     2714  4485  [[36.7375, 12.6375], [36.7375, 12.636667], [36...   
...    ...   ...                                                ...   
1854  4650  6199                                                NaN   
1855  4651  6197                                                NaN   
1856  4651  6198                                                NaN   
1857  4651  6200                                                NaN   
1858  4652  6199                                                NaN   

                                               geometry path_type  \
0     LINESTRING (36.73583 12.63917, 36.73667 12.638...        to   
1     LINESTRING (36.73583 12.63833, 36.73667 12.637...        to   
2     LINESTRING (36.73667 12.63833, 36.7375 12.6375...        to   
3     LINESTRING (36.73667 12.6375, 36.7375 12.63667...        to   
4     LINESTRING (36.7375 12.6375, 36.7375 12.63667,...        to   
...                                                 ...       ...   
1854  LINESTRING (38.16934 11.02024, 38.16719 11.017...      from   
1855  LINESTRING (38.16934 11.02024, 38.16719 11.017...      from   
1856  LINESTRING (38.16934 11.02024, 38.16719 11.017...      from   
1857  LINESTRING (38.16934 11.02024, 38.16719 11.017...      from   
1858  LINESTRING (38.16934 11.02024, 38.16719 11.017...      from   

                                        exit_point_path  
0                                                   NaN  
1                                                   NaN  
2                                                   NaN  
3                                                   NaN  
4                                                   NaN  
...                                                 ...  
1854  [[38.16934, 11.02024], [38.16719, 11.01785], [...  
1855  [[38.16934, 11.02024], [38.16719, 11.01785], [...  
1856  [[38.16934, 11.02024], [38.16719, 11.01785], [...  
1857  [[38.16934, 11.02024], [38.16719, 11.01785], [...  
1858  [[38.16934, 11.02024], [38.16719, 11.01785], [...  

[1859 rows x 6 columns]

In [35]:
paths["geometry"].explore()

In [14]:
path_to

array([array([41.670834,  9.505834], dtype=float32),
       array([41.67    ,  9.506667], dtype=float32),
       array([41.669167,  9.5075  ], dtype=float32),
       array([41.668335,  9.5075  ], dtype=float32),
       array([41.6675,  9.5075], dtype=float32),
       array([41.6675  ,  9.506667], dtype=float32),
       array([41.6675  ,  9.505834], dtype=float32),
       array([41.6675,  9.505 ], dtype=float32),
       array([41.66769,  9.50442], dtype=float32)], dtype=object)

In [15]:
path_from

array([array([41.66769,  9.50442], dtype=float32),
       array([41.67111,  9.49388], dtype=float32),
       array([41.69237,  9.50592], dtype=float32),
       array([41.69168,  9.5131 ], dtype=float32),
       array([41.69781,  9.51598], dtype=float32)], dtype=object)

In [15]:
print("hello")

hello


In [ ]:
et_bridge_view_gdf = convert_to_geodataframe(et_bridge_view)

In [34]:
test_gdf = prepare_columns_for_explore(et_bridge_view_gdf.head(1000), convert_cols)
test_gdf


index              type                  geometry subregion_indices   
0    302351  bridge_predicted  POINT (37.46229 4.84980)  [269620, 269629]  \
1    302352  bridge_predicted  POINT (37.46595 4.85105)  [269620, 270228]   
2    302353  bridge_predicted  POINT (37.46508 4.85778)  [269906, 270228]   
3    302354  bridge_predicted  POINT (37.45727 4.86828)  [267568, 269906]   
4    302355  bridge_predicted  POINT (37.45522 4.87006)  [267568, 269717]   
..      ...               ...                       ...               ...   
995  303346  bridge_predicted  POINT (37.46173 6.25181)  [269572, 270496]   
996  303347  bridge_predicted  POINT (37.47935 6.25766)  [270895, 271746]   
997  303348  bridge_predicted  POINT (37.46997 6.26019)  [270496, 270992]   
998  303349  bridge_predicted  POINT (37.43086 6.26919)  [266968, 267223]   
999  303350  bridge_predicted  POINT (37.42605 6.27567)  [266557, 266968]   

                  coords  exit_point_index   
0     [37.46229, 4.8498]            302352  \
1    [37.46595, 4.85105]            302353   
2    [37.46508, 4.85778]            302354   
3    [37.45727, 4.86828]            302355   
4    [37.45522, 4.87006]            302356   
..                   ...               ...   
995  [37.46173, 6.25181]            303347   
996  [37.47935, 6.25766]            303348   
997  [37.46997, 6.26019]            303349   
998  [37.43086, 6.26919]            303350   
999  [37.42605, 6.27567]            303351   

            used_by_cells_for_semi_dense_urban_optimal   
0    [array([12062,  5346]), array([12063,  5345]),...  \
1    [array([12099,  5344]), array([12099,  5345]),...   
2    [array([12099,  5344]), array([12099,  5345]),...   
3    [array([12099,  5344]), array([12099,  5345]),...   
4    [array([12028,  5319]), array([12029,  5318]),...   
..                                                 ...   
995  [array([10362,  5368]), array([10363,  5368]),...   
996  [array([10369,  5380]), array([10370,  5380]),...   
997  [array([10362,  5368]), array([10363,  5368]),...   
998  [array([10321,  5294]), array([10322,  5295]),...   
999  [array([10321,  5294]), array([10322,  5295]),...   

               used_by_h3_for_semi_dense_urban_optimal   
0    ['886a4b769bfffff', '886a4b769bfffff', '886a4b...  \
1    ['886a4b2b65fffff', '886a4b2b65fffff', '886a4b...   
2    ['886a4b2b65fffff', '886a4b2b65fffff', '886a4b...   
3    ['886a4b2b65fffff', '886a4b2b65fffff', '886a4b...   
4    ['886a4b3937fffff', '886a4b3937fffff', '886a4b...   
..                                                 ...   
995  ['886a49d623fffff', '886a49d623fffff', '886a49...   
996  ['886a49d635fffff', '886a49d635fffff', '886a49...   
997  ['886a49d623fffff', '886a49d623fffff', '886a49...   
998  ['886a4d6da9fffff', '886a4d6da9fffff', '886a4d...   
999  ['886a4d6da9fffff', '886a4d6da9fffff', '886a4d...   

                used_by_cells_for_health_posts_optimal   
0    [array([12062,  5346]), array([12063,  5345]),...  \
1    [array([12099,  5344]), array([12099,  5345]),...   
2    [array([12099,  5344]), array([12099,  5345]),...   
3    [array([12099,  5344]), array([12099,  5345]),...   
4    [array([12028,  5319]), array([12029,  5318]),...   
..                                                 ...   
995  [array([10370,  5349]), array([10370,  5350]),...   
996  [array([10414,  5390]), array([10415,  5390]),...   
997  [array([10370,  5349]), array([10370,  5350]),...   
998  [array([10354,  5331]), array([10355,  5332]),...   
999  [array([10345,  5283]), array([10345,  5284]),...   

                   used_by_h3_for_health_posts_optimal   
0    ['886a4b769bfffff', '886a4b769bfffff', '886a4b...  \
1    ['886a4b2b65fffff', '886a4b2b65fffff', '886a4b...   
2    ['886a4b2b65fffff', '886a4b2b65fffff', '886a4b...   
3    ['886a4b2b65fffff', '886a4b2b65fffff', '886a4b...   
4    ['886a4b3937fffff', '886a4b3937fffff', '886a4b...   
..                                                 ...   
995  ['886a49d719fffff', '886a4