In [10]:
import geopandas as gpd
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
import matplotlib.pyplot as plt
from shapely.geometry import LineString, Point
from shapely.ops import linemerge
import json
import os
import gc

In [2]:
# paths
local_path = "/Volumes/samsung-4tb/b2p/impact-model/no_order_1_less_than_500m_with_top_sites/model_outputs/"
path_data_path = "joined_data/travel_paths_to_all_education_facilities_fixed.parquet"
output_folder_path ="/Volumes/samsung-4tb/b2p/impact-model/cleaned_data/path_data/"

health_path = "joined_data/travel_paths_to_all_health_facilities_optimal.parquet"
edu_path = "joined_data/travel_paths_to_all_education_facilities_fixed.parquet"
market_path = "joined_data/travel_paths_to_semi_dense_urban_optimal.parquet"


et_path = os.path.join(local_path, "ethiopia/")
civ_path = os.path.join(local_path, "ivory_coast/")
kenya_path = os.path.join(local_path, "kenya/")
rwanda_path = os.path.join(local_path, "rwanda/")
tanzania_path = os.path.join(local_path, "tanzania/")
uganda_path = os.path.join(local_path, "uganda/")
zambia_path = os.path.join(local_path, "zambia/")


# Joining Data
This is memory intensive. there are probably better ways to do it.

In [9]:
# read each health data set by taking local path + each country path + health_path

et_health = pd.read_parquet(os.path.join(et_path, health_path))
print ("Ethiopia health data loaded:", et_health.shape)
civ_health = pd.read_parquet(os.path.join(civ_path, health_path))
print ("Ivory Coast health data loaded:", civ_health.shape)
kenya_health = pd.read_parquet(os.path.join(kenya_path, health_path))
print ("Kenya health data loaded:", kenya_health.shape)
rwanda_health = pd.read_parquet(os.path.join(rwanda_path, health_path))
print ("Rwanda health data loaded:", rwanda_health.shape)
uganda_health = pd.read_parquet(os.path.join(uganda_path, health_path))
print ("Uganda health data loaded:", uganda_health.shape)
zambia_health = pd.read_parquet(os.path.join(zambia_path, health_path))
print ("Zambia health data loaded:", zambia_health.shape)
tanzania_health = pd.read_parquet(os.path.join(tanzania_path, health_path))
print ("Tanzania health data loaded:", tanzania_health.shape)


Ethiopia health data loaded: (21679729, 16)
Ivory Coast health data loaded: (4965427, 16)
Kenya health data loaded: (10885694, 16)
Rwanda health data loaded: (1216780, 16)
Uganda health data loaded: (6579988, 16)
Zambia health data loaded: (9056513, 16)
Tanzania health data loaded: (17318913, 16)


In [11]:
health_data = pd.concat([et_health, civ_health, kenya_health, rwanda_health, uganda_health, zambia_health, tanzania_health], ignore_index=True)
print("All health data combined:", health_data.shape)

health_data.to_parquet(os.path.join(output_folder_path, "all_health_paths.parquet"), index=False)
# clean up memory
gc.collect()

All health data combined: (71703044, 16)


1702

In [3]:
# read each edu data set by taking local path + each country path + edu_path
et_edu = pd.read_parquet(os.path.join(et_path, edu_path))
print ("Ethiopia education data loaded:", et_edu.shape)
civ_edu = pd.read_parquet(os.path.join(civ_path, edu_path))
print ("Ivory Coast education data loaded:", civ_edu.shape)
kenya_edu = pd.read_parquet(os.path.join(kenya_path, edu_path))
print ("Kenya education data loaded:", kenya_edu.shape)
rwanda_edu = pd.read_parquet(os.path.join(rwanda_path, edu_path))
print ("Rwanda education data loaded:", rwanda_edu.shape)
tanzania_edu = pd.read_parquet(os.path.join(tanzania_path, edu_path))
print ("Tanzania education data loaded:", tanzania_edu.shape)
uganda_edu = pd.read_parquet(os.path.join(uganda_path, edu_path))
print ("Uganda education data loaded:", uganda_edu.shape)
zambia_edu = pd.read_parquet(os.path.join(zambia_path, edu_path))
print ("Zambia education data loaded:", zambia_edu.shape)

Ethiopia education data loaded: (21675173, 15)
Ivory Coast education data loaded: (4964083, 15)
Kenya education data loaded: (10892486, 15)
Rwanda education data loaded: (1217081, 15)
Tanzania education data loaded: (17327625, 15)
Uganda education data loaded: (6581637, 15)
Zambia education data loaded: (9057963, 15)


In [4]:
edu_data = pd.concat([et_edu, civ_edu, kenya_edu, rwanda_edu, tanzania_edu, uganda_edu, zambia_edu], ignore_index=True)
print("All education data combined:", edu_data.shape)
edu_data.to_parquet(os.path.join(output_folder_path, "all_education_paths.parquet"), index=False)
# clean up memory
gc.collect()

All education data combined: (71716048, 15)


0

In [7]:
et_market = pd.read_parquet(os.path.join(et_path, market_path))
print ("Ethiopia market data loaded:", et_market.shape)
civ_market = pd.read_parquet(os.path.join(civ_path, market_path))
print ("Ivory Coast market data loaded:", civ_market.shape)
kenya_market = pd.read_parquet(os.path.join(kenya_path, market_path))
print ("Kenya market data loaded:", kenya_market.shape)
rwanda_market = pd.read_parquet(os.path.join(rwanda_path, market_path))
print ("Rwanda market data loaded:", rwanda_market.shape)
tanzania_market = pd.read_parquet(os.path.join(tanzania_path, market_path))
print ("Tanzania market data loaded:", tanzania_market.shape)
uganda_market = pd.read_parquet(os.path.join(uganda_path, market_path))
print ("Uganda market data loaded:", uganda_market.shape)

Ethiopia market data loaded: (21677026, 16)
Ivory Coast market data loaded: (4964062, 16)
Kenya market data loaded: (10883344, 16)
Rwanda market data loaded: (1216658, 16)
Tanzania market data loaded: (17317885, 16)
Uganda market data loaded: (6579468, 16)


In [8]:
market_data = pd.concat([et_market, civ_market, kenya_market, rwanda_market, tanzania_market, uganda_market], ignore_index=True)
print("All market data combined:", market_data.shape)
market_data.to_parquet(os.path.join(output_folder_path, "all_market_paths.parquet"), index=False)
# clean up memory
gc.collect()

All market data combined: (62638443, 16)


1251

In [9]:
market_data

row   col  subregion                  coords      exit_point_used  \
0         12427  8836     586947  [40.363335, 4.5433335]                 None   
1         12427  8837     586947  [40.364166, 4.5433335]                 None   
2         12427  8838     586947     [40.365, 4.5433335]                 None   
3         12427  8839     586947  [40.365833, 4.5433335]                 None   
4         12428  8836     586947     [40.363335, 4.5425]                 None   
...         ...   ...        ...                     ...                  ...   
62638438   1907  1621      42104    [30.9225, 2.6450002]  [30.92593, 2.64645]   
62638439   1907  1622      42104  [30.923334, 2.6450002]  [30.92593, 2.64645]   
62638440   1907  1624      42104     [30.925, 2.6450002]  [30.92593, 2.64645]   
62638441   1907  1625      42104     [30.92593, 2.64461]  [30.92593, 2.64461]   
62638442   1907  1626      42104  [30.926666, 2.6450002]  [30.92593, 2.64645]   

          exit_point_index  destination_index   destination_coords  \
0                        0                  0                 None   
1                        0                  0                 None   
2                        0                  0                 None   
3                        0                  0                 None   
4                        0                  0                 None   
...                    ...                ...                  ...   
62638438            156451               1020  [30.94625, 2.72625]   
62638439            156451               1020  [30.94625, 2.72625]   
62638440            156451               1020  [30.94625, 2.72625]   
62638441            156452               1020  [30.94625, 2.72625]   
62638442            156451               1020  [30.94625, 2.72625]   

                                      exit_point_index_path         h3_index  \
0                                                      None  887aeeba5dfffff   
1                                                      None  887aeeba5dfffff   
2                                                      None  887aeeba5dfffff   
3                                                      None  887aeeba5dfffff   
4                                                      None  887aeeba5dfffff   
...                                                     ...              ...   
62638438  [156451, 156450, 156449, 156458, 156457, 15645...  886aee0339fffff   
62638439  [156451, 156450, 156449, 156458, 156457, 15645...  886aee0339fffff   
62638440  [156451, 156450, 156449, 156458, 156457, 15645...  886aee0339fffff   
62638441  [156452, 156451, 156450, 156449, 156458, 15645...  886aee0339fffff   
62638442  [156451, 156450, 156449, 156458, 156457, 15645...  886aee0339fffff   

                                            exit_point_path  \
0                                                      None   
1                                                      None   
2                                                      None   
3                                                      None   
4                                                      None   
...                                                     ...   
62638438  [[30.92593, 2.64645], [30.92592, 2.64956], [30...   
62638439  [[30.92593, 2.64645], [30.92592, 2.64956], [30...   
62638440  [[30.92593, 2.64645], [30.92592, 2.64956], [30...   
62638441  [[30.92593, 2.64461], [30.92593, 2.64645], [30...   
62638442  [[30.92593, 2.64645], [30.92592, 2.64956], [30...   

                                         path_to_exit_point  \
0                                                        []   
1                                                        []   
2                                                        []   
3                                                        []   
4                                                        []   
...                                                     ...   
62638438  [[30.9225, 2.6450002], [30.92

# Cleaning path data
one of the major cleaning operations is going through all the paths that go from an h3 index to the same destination. I'll be keeping the longest path

In [6]:
def keep_longest_path(df):
    df = df.copy()
    print("Original df shape:", df.shape)
    
    # Drop rows with None in destination_coords
    df = df.dropna(subset=['destination_coords'])
    print("After dropping None coords:", df.shape)
    
    df['coords_str'] = df['destination_coords'].apply(lambda x: str(x.tolist()) if hasattr(x, 'tolist') else str(x))
    df['path_length'] = df['exit_point_path'].str.len()
    
    # Drop rows where exit_point_path is None/NaN (which would make path_length NaN)
    df = df.dropna(subset=['path_length'])
    print("After dropping NaN path lengths:", df.shape)
    
    idx = df.groupby(['h3_index', 'coords_str'])['path_length'].idxmax()
    # Drop any NaN indices
    idx = idx.dropna()
    
    result = df.loc[idx].drop(['path_length', 'coords_str'], axis=1)
    
    print("Result df shape:", result.shape)
    print("Rows removed:", df.shape[0] - result.shape[0])
    
    return result

In [28]:
market_data_clean = keep_longest_path(market_data)

Original df shape: (62638443, 17)
After dropping None coords: (53214778, 17)
After dropping NaN path lengths: (51473125, 18)
Result df shape: (2758892, 16)
Rows removed: 48714233


In [30]:
market_data_clean.to_parquet(os.path.join(output_folder_path, "all_market_paths.parquet"), index=False)


In [3]:
health_data_full = pd.read_parquet(os.path.join(output_folder_path, "all_health_paths.parquet"))

In [7]:
health_data_clean = keep_longest_path(health_data_full)

Original df shape: (3874481, 16)
After dropping None coords: (3874481, 16)
After dropping NaN path lengths: (3874481, 18)
Result df shape: (3874481, 16)
Rows removed: 0


In [8]:
health_data_clean

row    col  subregion                   coords  \
0         2173   6678     383896      [38.565, 13.088333]   
1         2176   6693     386106     [38.5775, 13.085834]   
2         2176   6673     383896   [38.560833, 13.085834]   
3         2180   6683     384586     [38.569168, 13.0825]   
4         2160   6678     384185      [38.565, 13.099167]   
...        ...    ...        ...                      ...   
3874476  11623  11337     440237     [38.775, -10.668333]   
3874477  11618  11324     440237    [38.76421, -10.66389]   
3874478  11638  11328     440237  [38.767796, -10.681157]   
3874479  11634  11318     440237  [38.759434, -10.677457]   
3874480  11632  11337     440237     [38.775, -10.675833]   

               exit_point_used  exit_point_index  destination_index  \
0         [38.56033, 13.08483]            876063               1504   
1         [38.57775, 13.08414]             67455               1504   
2         [38.56033, 13.08483]            876063               1504   
3          [38.56224, 13.0697]            550751               1504   
4         [38.56495, 13.10014]            876681               1504   
...                        ...               ...                ...   
3874476  [38.78089, -10.65889]            364219               3390   
3874477  [38.76421, -10.66389]            710632               3559   
3874478  [38.78194, -10.69334]            359880               3483   
3874479  [38.78194, -10.69334]            359880               3483   
3874480  [38.78194, -10.69334]            359880               3483   

            destination_coords  \
0         [38.52223, 13.08687]   
1         [38.52223, 13.08687]   
2         [38.52223, 13.08687]   
3         [38.52223, 13.08687]   
4         [38.52223, 13.08687]   
...                        ...   
3874476  [38.81431, -10.62963]   
3874477  [38.69677, -10.63063]   
3874478     [38.796, -10.7319]   
3874479     [38.796, -10.7319]   
3874480     [38.796, -10.7319]   

                                     exit_point_index_path         h3_index  \
0        [876063, 1086283, 407312, 566356, 344875, 8751...  8852800001fffff   
1        [67455, 376915, 514780, 618931, 550751, 392145...  8852800003fffff   
2        [876063, 1086283, 407312, 566356, 344875, 8751...  8852800005fffff   
3        [550751, 392145, 566356, 344875, 875178, 51945...  8852800007fffff   
4        [876681, 508811, 603173, 877186, 506967, 54387...  8852800009fffff   
...                                                    ...              ...   
3874476                   [364219, 364337, 367032, 367033]  88979edb65fffff   
3874477   [710632, 364643, 226611, 226610, 226609, 226608]  88979edb67fffff   
3874478                                   [359880, 359737]  88979edb69fffff   
3874479                                   [359880, 359737]  88979edb6bfffff   
3874480                                   [359880, 359737]  88979edb6dfffff   

                                           exit_point_path  \
0        [[38.56033, 13.08483], [38.55622, 13.075], [38...   
1        [[38.57775, 13.08414], [38.56982, 13.07001], [...   
2        [[38.56033, 13.08483], [38.55622, 13.075], [38...   
3        [[38.56224, 13.0697], [38.55791, 13.07237], [3...   
4        [[38.56495, 13.10014], [38.56265, 13.10264], [...   
...                                                    ...   
3874476  [[38.78089, -10.65889], [38.79557, -10.66158],...   
3874477  [[38.76421, -10.66389], [38.75923, -10.66722],...   
3874478  [[38.78194, -10.69334], [38.79418, -10.72445],...   
3874479  [[38.78194, -10.69334], [38.79418, -10.72445],...   
3874480  [[38.78194, -10.69334], [38.79418, -10.72445],...   

                                        path_to_exit_point  \
0        [[38.565, 13.088333], [38.564167, 13.087501], ...   
1        [[38.5775, 13.085834], [38.5775, 13.085], [38....   
2           [[38.560833, 13.085834], [38.56033, 13.08483]]   
3        [[38.569168, 13.0825], [38.569168, 13.081667],...   
4           

In [9]:
health_data_clean.to_parquet(os.path.join(output_folder_path, "all_health_paths.parquet"), index=False)

In [10]:
# clear memory
gc.collect()

20

In [11]:
edu_data_full = pd.read_parquet(os.path.join(output_folder_path, "all_education_paths.parquet"))

In [12]:
edu_data_clean = keep_longest_path(edu_data_full)

Original df shape: (71716048, 15)
After dropping None coords: (61232911, 15)
After dropping NaN path lengths: (51968234, 17)
Result df shape: (3466420, 15)
Rows removed: 48501814


In [13]:
edu_data_clean

row    col  subregion                   coords  \
12175069   2173   6678     383896      [38.565, 13.088333]   
6651791    2178   6693     385380   [38.577747, 13.084141]   
12175081   2176   6673     383896   [38.560833, 13.085834]   
4740169    2180   6683     384586     [38.569168, 13.0825]   
12401972   2162   6683     384185     [38.569168, 13.0975]   
...         ...    ...        ...                      ...   
49302148  11632  11322     440237   [38.76278, -10.676222]   
49302080  11623  11318     440237  [38.759167, -10.668333]   
49302089  11624  11319     440237      [38.76, -10.669167]   
49302063  11618  11324     440237    [38.76421, -10.66389]   
49302167  11634  11318     440237  [38.759434, -10.677457]   

                exit_point_used  exit_point_index  destination_index  \
12175069   [38.56033, 13.08483]            876063               1437   
6651791    [38.57775, 13.08414]             67455               1437   
12175081   [38.56033, 13.08483]            876063               1437   
4740169     [38.56224, 13.0697]            550751               1437   
12401972   [38.57014, 13.09875]            876680               1437   
...                         ...               ...                ...   
49302148  [38.74946, -10.67406]            367271              10875   
49302080  [38.75639, -10.66906]            226612              10874   
49302089  [38.74946, -10.67406]            367271              10875   
49302063  [38.76421, -10.66389]            710632              10874   
49302167  [38.74988, -10.67588]            276284              10875   

             destination_coords  \
12175069   [38.46577, 13.17027]   
6651791    [38.46577, 13.17027]   
12175081   [38.46577, 13.17027]   
4740169    [38.46577, 13.17027]   
12401972   [38.46577, 13.17027]   
...                         ...   
49302148  [38.74636, -10.67675]   
49302080  [38.74636, -10.66944]   
49302089  [38.74636, -10.67675]   
49302063  [38.74636, -10.66944]   
49302167  [38.74636, -10.67675]   

                                      exit_point_index_path         h3_index  \
12175069  [876063, 1086283, 407312, 566356, 344875, 8751...  8852800001fffff   
6651791   [67455, 619859, 511176, 489193, 876681, 508811...  8852800003fffff   
12175081  [876063, 1086283, 407312, 566356, 344875, 8751...  8852800005fffff   
4740169   [550751, 392145, 566356, 344875, 875178, 51945...  8852800007fffff   
12401972  [876680, 886026, 508811, 603173, 877186, 50696...  8852800009fffff   
...                                                     ...              ...   
49302148                                           [367271]  88979edb61fffff   
49302080                                           [226612]  88979edb63fffff   
49302089                                           [367271]  88979edb63fffff   
49302063                                   [710632, 364643]  88979edb67fffff   
49302167                                           [276284]  88979edb6bfffff   

                                            exit_point_path  \
12175069  [[38.56033, 13.08483], [38.55622, 13.075], [38...   
6651791   [[38.57775, 13.08414], [38.57785, 13.09055], [...   
12175081  [[38.56033, 13.08483], [38.55622, 13.075], [38...   
4740169   [[38.56224, 13.0697], [38.55791, 13.07237], [3...   
12401972  [[38.57014, 13.09875], [38.57023, 13.10083], [...   
...                                                     ...   
49302148     [[38.74946, -10.67406], [38.74636, -10.67675]]   
49302080     [[38.75639, -10.66906], [38.74636, -10.66944]]   
49302089     [[38.74946, -10.67406], [38.74636, -10.67675]]   
49302063  [[38.76421, -10.66389], [38.75923, -10.66722],...   
49302167     [[38.74988, -10.67588], [38.74636, -10.67675]]   

                                         path_to_exit_point  \
12175069  [[38.565, 13.088333], [38.564167, 13.087501], ...   
6651791      [[38.577747, 13.084141], [38.57775, 13.08414]]   
12175081     [[38.560833, 13.085834], [38.56033, 13.08483]]   
4740169   [

In [14]:
edu_data_clean.to_parquet(os.path.join(output_folder_path, "all_education_paths.parquet"), index=False)

# Transforming Paths to Geospatial Data

In [3]:
health_paths = pd.read_parquet(os.path.join(output_folder_path, "all_health_paths.parquet"))

In [7]:
print(health_paths["exit_point_path"][0])

[array([38.56033, 13.08483], dtype=float32)
 array([38.55622, 13.075  ], dtype=float32)
 array([38.55559, 13.07476], dtype=float32)
 array([38.55367, 13.07134], dtype=float32)
 array([38.54392, 13.06961], dtype=float32)
 array([38.53478, 13.07654], dtype=float32)
 array([38.53266, 13.07879], dtype=float32)
 array([38.52726, 13.07931], dtype=float32)
 array([38.52541, 13.08086], dtype=float32)
 array([38.52223, 13.08687], dtype=float32)]


In [6]:
health_paths

row    col  subregion                   coords  \
0         2173   6678     383896      [38.565, 13.088333]   
1         2176   6693     386106     [38.5775, 13.085834]   
2         2176   6673     383896   [38.560833, 13.085834]   
3         2180   6683     384586     [38.569168, 13.0825]   
4         2160   6678     384185      [38.565, 13.099167]   
...        ...    ...        ...                      ...   
3874476  11623  11337     440237     [38.775, -10.668333]   
3874477  11618  11324     440237    [38.76421, -10.66389]   
3874478  11638  11328     440237  [38.767796, -10.681157]   
3874479  11634  11318     440237  [38.759434, -10.677457]   
3874480  11632  11337     440237     [38.775, -10.675833]   

               exit_point_used  exit_point_index  destination_index  \
0         [38.56033, 13.08483]            876063               1504   
1         [38.57775, 13.08414]             67455               1504   
2         [38.56033, 13.08483]            876063               1504   
3          [38.56224, 13.0697]            550751               1504   
4         [38.56495, 13.10014]            876681               1504   
...                        ...               ...                ...   
3874476  [38.78089, -10.65889]            364219               3390   
3874477  [38.76421, -10.66389]            710632               3559   
3874478  [38.78194, -10.69334]            359880               3483   
3874479  [38.78194, -10.69334]            359880               3483   
3874480  [38.78194, -10.69334]            359880               3483   

            destination_coords  \
0         [38.52223, 13.08687]   
1         [38.52223, 13.08687]   
2         [38.52223, 13.08687]   
3         [38.52223, 13.08687]   
4         [38.52223, 13.08687]   
...                        ...   
3874476  [38.81431, -10.62963]   
3874477  [38.69677, -10.63063]   
3874478     [38.796, -10.7319]   
3874479     [38.796, -10.7319]   
3874480     [38.796, -10.7319]   

                                     exit_point_index_path         h3_index  \
0        [876063, 1086283, 407312, 566356, 344875, 8751...  8852800001fffff   
1        [67455, 376915, 514780, 618931, 550751, 392145...  8852800003fffff   
2        [876063, 1086283, 407312, 566356, 344875, 8751...  8852800005fffff   
3        [550751, 392145, 566356, 344875, 875178, 51945...  8852800007fffff   
4        [876681, 508811, 603173, 877186, 506967, 54387...  8852800009fffff   
...                                                    ...              ...   
3874476                   [364219, 364337, 367032, 367033]  88979edb65fffff   
3874477   [710632, 364643, 226611, 226610, 226609, 226608]  88979edb67fffff   
3874478                                   [359880, 359737]  88979edb69fffff   
3874479                                   [359880, 359737]  88979edb6bfffff   
3874480                                   [359880, 359737]  88979edb6dfffff   

                                           exit_point_path  \
0        [[38.56033, 13.08483], [38.55622, 13.075], [38...   
1        [[38.57775, 13.08414], [38.56982, 13.07001], [...   
2        [[38.56033, 13.08483], [38.55622, 13.075], [38...   
3        [[38.56224, 13.0697], [38.55791, 13.07237], [3...   
4        [[38.56495, 13.10014], [38.56265, 13.10264], [...   
...                                                    ...   
3874476  [[38.78089, -10.65889], [38.79557, -10.66158],...   
3874477  [[38.76421, -10.66389], [38.75923, -10.66722],...   
3874478  [[38.78194, -10.69334], [38.79418, -10.72445],...   
3874479  [[38.78194, -10.69334], [38.79418, -10.72445],...   
3874480  [[38.78194, -10.69334], [38.79418, -10.72445],...   

                                        path_to_exit_point  \
0        [[38.565, 13.088333], [38.564167, 13.087501], ...   
1        [[38.5775, 13.085834], [38.5775, 13.085], [38....   
2           [[38.560833, 13.085834], [38.56033, 13.08483]]   
3        [[38.569168, 13.0825], [38.569168, 13.081667],...   
4           

In [ ]:
# Convert the exit_point_path column to LineString geometries
health_paths['geometry'] = health_paths['exit_point_path'].apply( lambda path: LineString(np.array([np.array(point) for point in path])) )
health_paths

row    col  subregion                   coords  \
0         2173   6678     383896      [38.565, 13.088333]   
1         2176   6693     386106     [38.5775, 13.085834]   
2         2176   6673     383896   [38.560833, 13.085834]   
3         2180   6683     384586     [38.569168, 13.0825]   
4         2160   6678     384185      [38.565, 13.099167]   
...        ...    ...        ...                      ...   
3874476  11623  11337     440237     [38.775, -10.668333]   
3874477  11618  11324     440237    [38.76421, -10.66389]   
3874478  11638  11328     440237  [38.767796, -10.681157]   
3874479  11634  11318     440237  [38.759434, -10.677457]   
3874480  11632  11337     440237     [38.775, -10.675833]   

               exit_point_used  exit_point_index  destination_index  \
0         [38.56033, 13.08483]            876063               1504   
1         [38.57775, 13.08414]             67455               1504   
2         [38.56033, 13.08483]            876063               1504   
3          [38.56224, 13.0697]            550751               1504   
4         [38.56495, 13.10014]            876681               1504   
...                        ...               ...                ...   
3874476  [38.78089, -10.65889]            364219               3390   
3874477  [38.76421, -10.66389]            710632               3559   
3874478  [38.78194, -10.69334]            359880               3483   
3874479  [38.78194, -10.69334]            359880               3483   
3874480  [38.78194, -10.69334]            359880               3483   

            destination_coords  \
0         [38.52223, 13.08687]   
1         [38.52223, 13.08687]   
2         [38.52223, 13.08687]   
3         [38.52223, 13.08687]   
4         [38.52223, 13.08687]   
...                        ...   
3874476  [38.81431, -10.62963]   
3874477  [38.69677, -10.63063]   
3874478     [38.796, -10.7319]   
3874479     [38.796, -10.7319]   
3874480     [38.796, -10.7319]   

                                     exit_point_index_path         h3_index  \
0        [876063, 1086283, 407312, 566356, 344875, 8751...  8852800001fffff   
1        [67455, 376915, 514780, 618931, 550751, 392145...  8852800003fffff   
2        [876063, 1086283, 407312, 566356, 344875, 8751...  8852800005fffff   
3        [550751, 392145, 566356, 344875, 875178, 51945...  8852800007fffff   
4        [876681, 508811, 603173, 877186, 506967, 54387...  8852800009fffff   
...                                                    ...              ...   
3874476                   [364219, 364337, 367032, 367033]  88979edb65fffff   
3874477   [710632, 364643, 226611, 226610, 226609, 226608]  88979edb67fffff   
3874478                                   [359880, 359737]  88979edb69fffff   
3874479                                   [359880, 359737]  88979edb6bfffff   
3874480                                   [359880, 359737]  88979edb6dfffff   

                                           exit_point_path  \
0        [[38.56033, 13.08483], [38.55622, 13.075], [38...   
1        [[38.57775, 13.08414], [38.56982, 13.07001], [...   
2        [[38.56033, 13.08483], [38.55622, 13.075], [38...   
3        [[38.56224, 13.0697], [38.55791, 13.07237], [3...   
4        [[38.56495, 13.10014], [38.56265, 13.10264], [...   
...                                                    ...   
3874476  [[38.78089, -10.65889], [38.79557, -10.66158],...   
3874477  [[38.76421, -10.66389], [38.75923, -10.66722],...   
3874478  [[38.78194, -10.69334], [38.79418, -10.72445],...   
3874479  [[38.78194, -10.69334], [38.79418, -10.72445],...   
3874480  [[38.78194, -10.69334], [38.79418, -10.72445],...   

                                        path_to_exit_point  \
0        [[38.565, 13.088333], [38.564167, 13.087501], ...   
1        [[38.5775, 13.085834], [38.5775, 13.085], [38....   
2           [[38.560833, 13.085834], [38.56033, 13.08483]]   
3        [[38.569168, 13.0825], [38.569168, 13.081667],...   
4           

In [ ]:
def paths_to_geodataframe(df):
   def safe_linestring(path):
       if len(path) < 2:  # Drop if 0 or 1 points
           return None
       else:
           return LineString(np.array([np.array(point) for point in path]))

   # Convert both columns, keeping only valid LineStrings
   df['exit_geometry'] = df['exit_point_path'].apply(safe_linestring)
   df['path_geometry'] = df['path_to_exit_point'].apply(safe_linestring)

   # Only keep rows where at least one geometry is valid
   mask = (df['exit_geometry'].notna()) | (df['path_geometry'].notna())
   df_filtered = df[mask].copy()

   # Join geometries (only LineStrings now)
   def safe_merge(row):
       geoms = [g for g in [row['path_geometry'], row['exit_geometry']] if g is not None]
       if len(geoms) == 1:
           return geoms[0]
       else:
           return linemerge(geoms)

   df_filtered['geometry'] = df_filtered.apply(safe_merge, axis=1)
   
   # Convert to GeoDataFrame
   return gpd.GeoDataFrame(df_filtered, geometry='geometry')

In [ ]:
gdf = paths_to_geodataframe(health_paths)
gdf = gdf.set_crs(epsg=4326, allow_override=True)
gdf = gdf.drop(columns=['exit_point_path', 'path_to_exit_point', 'exit_geometry', 'path_geometry'])
gdf.to_parquet(os.path.join(output_folder_path, "all_health_paths_geodataframe.parquet"), index=False)

In [29]:
edu_paths = pd.read_parquet(os.path.join(output_folder_path, "all_education_paths.parquet"))
print("edu paths read")
gdf = paths_to_geodataframe(edu_paths)
print("edu paths converted to geodataframe")
gdf = gdf.set_crs(epsg=4326, allow_override=True)
gdf = gdf.drop(columns=['exit_point_path', 'path_to_exit_point', 'exit_geometry', 'path_geometry'])
print("writing edu paths to parquet")
gdf.to_parquet(os.path.join(output_folder_path, "all_education_paths_geodataframe.parquet"), index=False)

edu paths read
edu paths converted to geodataframe
writing edu paths to parquet


In [30]:
market_paths = pd.read_parquet(os.path.join(output_folder_path, "all_market_paths.parquet"))
print("market paths read")
gdf = paths_to_geodataframe(market_paths)
print("market paths converted to geodataframe")
gdf = gdf.set_crs(epsg=4326, allow_override=True)
gdf = gdf.drop(columns=['exit_point_path', 'path_to_exit_point', 'exit_geometry', 'path_geometry'])
print("writing market paths to parquet")
gdf.to_parquet(os.path.join(output_folder_path, "all_market_paths_geodataframe.parquet"), index=False)

market paths read
market paths converted to geodataframe
writing market paths to parquet
